// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureChatChatMicroService.Infrastructure;

#nullable disable

namespace SecureChatChatMicroService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatServiceDbContext))]
    [Migration("20260503081625_ChatMicroService_Migration_0.0.3")]
    partial class ChatMicroService_Migration_003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ChatMicroService")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Удален ли");

                    b.Property<Instant?>("LastMessageTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата последнего сообщения");

                    b.Property<Guid>("Type")
                        .HasColumnType("uuid")
                        .HasColumnName("Type")
                        .HasComment("Тип (чат, канал, группа)");

                    b.HasKey("Id");

                    b.ToTable("Chats", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.ChatGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("ChatId")
                        .HasComment("Ид чата");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("GroupId")
                        .HasComment("Ид группы");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("GroupId");

                    b.ToTable("ChatGroup", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.ChatParticipantsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("EnterTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата входа");

                    b.Property<Instant?>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата выхода");

                    b.Property<bool>("IsMuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Есть ли уведомления от чата у пользователя");

                    b.Property<bool>("IsPint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Закреплен ли чат у пользователя");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatParticipants", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name")
                        .HasComment("Название");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnswerMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата удаления");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Удалено ли");

                    b.Property<Instant>("SendTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SendTime")
                        .HasComment("Дата отправки");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Текст сообщения");

                    b.Property<Instant?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата изменения");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnswerMessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Удален ли");

                    b.HasKey("UserId");

                    b.ToTable("Users", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Enums.ChatTypeEnum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Тип чата");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("ChatTypes", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Enums.TypeOfMessageEnum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Тип сообщения");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TypeOfMessages", "ChatMicroService");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.ChatGroupEntity", b =>
                {
                    b.HasOne("SecureChatChatMicroService.Domain.Entities.ChatEntity", "Chat")
                        .WithMany("ChatGroups")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChatChatMicroService.Domain.Entities.GroupEntity", "Group")
                        .WithMany("ChatGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.ChatParticipantsEntity", b =>
                {
                    b.HasOne("SecureChatChatMicroService.Domain.Entities.ChatEntity", "Chat")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SecureChatChatMicroService.Domain.Entities.UserEntity", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.GroupEntity", b =>
                {
                    b.HasOne("SecureChatChatMicroService.Domain.Entities.UserEntity", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.MessageEntity", b =>
                {
                    b.HasOne("SecureChatChatMicroService.Domain.Entities.MessageEntity", "AnswerMessage")
                        .WithMany("RepliesMessage")
                        .HasForeignKey("AnswerMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SecureChatChatMicroService.Domain.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SecureChatChatMicroService.Domain.Entities.UserEntity", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnswerMessage");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.ChatEntity", b =>
                {
                    b.Navigation("ChatGroups");

                    b.Navigation("ChatParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.GroupEntity", b =>
                {
                    b.Navigation("ChatGroups");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.MessageEntity", b =>
                {
                    b.Navigation("RepliesMessage");
                });

            modelBuilder.Entity("SecureChatChatMicroService.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("Groups");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
