<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Api.CommonProtos" Version="2.16.0"/>
        <PackageReference Include="Google.Protobuf" Version="3.29.3"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.67.0"/>
        <PackageReference Include="Grpc.AspNetCore.Server" Version="2.67.0"/>
        <PackageReference Include="Grpc.AspNetCore.Server.ClientFactory" Version="2.67.0"/>
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.67.0"/>
        <PackageReference Include="Grpc.AspNetCore.Web" Version="2.67.0"/>
        <PackageReference Include="Grpc.Core.Api" Version="2.67.0"/>
        <PackageReference Include="Grpc.Tools" Version="2.69.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="ChatMicroService\Common\*.proto" GrpcServices="None"
                  ProtoRoot="ChatMicroService" />
        <Protobuf Include="ChatMicroService\UserProtos\user-service.proto" GrpcServices="Both"
                  ProtoRoot="ChatMicroService"/>
        <Protobuf Include="ChatMicroService\GroupProtos\group-service.proto" GrpcServices="Both"
                  ProtoRoot="ChatMicroService"/>
        <Protobuf Include="ChatMicroService\ChatParticipantsProtos\chat-participants-service.proto" GrpcServices="Both"
                  ProtoRoot="ChatMicroService"/>
        <Protobuf Include="ChatMicroService\ChatGroupProtos\chat-group-service.proto" GrpcServices="Both" ProtoRoot="ChatMicroService" />
        <Protobuf Include="ChatMicroService\ChatProtos\chat-service.proto" GrpcServices="Both"
                  ProtoRoot="ChatMicroService"/>
        <Protobuf Include="ChatMicroService\MessageProtos\message-service.proto" GrpcServices="Both"
                  ProtoRoot="ChatMicroService"/>
    </ItemGroup>

    <PropertyGroup>
        <ProtoRoot>ChatMicroService</ProtoRoot>
    </PropertyGroup>
</Project>
