syntax = "proto3";

package common;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "ChatMicroService.Common";

// Информация о пользователях
message UserInfo{
  string Id = 1;
  string UserProfileId = 2;
  bool IsDeleted = 3;
  repeated GroupInfo Groups = 4;
}

// Информация о группах
message GroupInfo{
  string Id = 1;
  string Name = 2;
  string UserId = 3;
  repeated ChatGroupInfo ChatGroups = 4;
}

// Информация о чат-группах
message ChatGroupInfo {
  string Id = 1;
  string ChatId = 2;
  string GroupId = 3;
}

// Информация о чатах
message ChatInfo{
  string Id = 1;
  google.protobuf.Timestamp LastMessageTime = 2;
  int32 CountUnreadMessages = 3;
  bool IsPint = 4;
  bool IsMute = 5;
  bool IsDeleted = 6;
  string Type = 7;
  optional  string OwnerId = 8;
  repeated  common.ChatGroupInfo ChatGroups = 9;
  repeated  ChatParticipantsInfo ChatParticipants = 10;
  repeated  MessageInfo Messages = 11;
}

// Информация об участниках чата
message ChatParticipantsInfo{
  string Id = 1;
  google.protobuf.Timestamp EnterTime = 2;
  optional  google.protobuf.Timestamp ExitTime = 3;
  string ChatId = 4;
  string UserId = 5;
}

// Информация о сообщениях
message MessageInfo{
  string Id = 1;
  optional string AnswerMessageId = 2;
  string ChatId = 3;
  string UserId = 4;
  string TypeOfMessage = 5;
  string Content = 6;
  google.protobuf.Timestamp SendTime = 7;
  optional google.protobuf.Timestamp UpdateTime = 8;
  optional google.protobuf.Timestamp DeleteTime = 9;
  bool IsEdited = 10;
  bool IsDeleted = 11;
}
