syntax = "proto3";

import "google/api/annotations.proto";
import "Common/chat_microservice_commons.proto";

option csharp_namespace = "MessageService.Proto";

// 
service MessageGrpcService {
  rpc CreateMessage(CreateMessageRequest) returns (CreateMessageResponse) {
    option (google.api.http) = {
      post: "/grpc/message/add"
      body: "*"
    };
  }
  rpc GetMessages(GetMessagesRequest) returns (GetMessagesResponse) {
    option (google.api.http) = {get: "/grpc/messages"};
  }
  rpc GetMessage(GetMessageRequest) returns (GetMessageResponse) {
    option (google.api.http) = {get: "/grpc/message/{Id}"};
  }
  rpc UpdateMessage(UpdateMessageRequest) returns (UpdateMessageResponse) {
    option (google.api.http) = {
      put: "/grpc/message/{Id}"
      body: "*"
    };
  }
  rpc DeleteMessage(DeleteMessageRequest) returns (DeleteMessageResponse) {
    option (google.api.http) = {delete: "/grpc/message/{Id}"};
  }
}

/*REQUEST*/
// 
message GetMessagesRequest{
  string ChatId = 1;
}

// 
message GetMessageRequest{
  string Id = 1;
}

// 
message CreateMessageRequest{
  // 
  optional string AnswerMessageId = 1;
  string ChatId = 2;
  string UserId = 3;
  string TypeOfMessage = 4;
  string Content = 5;
}

// 
message UpdateMessageRequest{
  string Id = 1;
  optional string Content = 2;
}

// 
message DeleteMessageRequest{
  string Id = 1;
}

/*RESPONSE*/
// 
message GetMessagesResponse {
  // 
  bool Success = 1;
  // 
  repeated common.MessageInfo Messages = 2;
}

// 
message GetMessageResponse {
  // 
  bool Success = 1;
  // 
  common.MessageInfo Messages = 2;
}

// 
message CreateMessageResponse {
  // 
  bool Success = 1;
  // 
  string Id = 2;
}

// 
message UpdateMessageResponse {
  // 
  bool Success = 1;
  // 
  common.MessageInfo UpdateMessage = 2;
}

// 
message DeleteMessageResponse {
  // 
  bool Success = 1;
}